//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeSystemKeremGokgoz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipesTable
    {
        public int RecId { get; set; }
        public int UserId { get; set; }
        public int CatId { get; set; }
        public string RecTitle { get; set; }
        public byte[] Images { get; set; }
        public string RecDetails { get; set; }
    
        public virtual CategoriesTable CategoriesTable { get; set; }
        public virtual UsersTable UsersTable { get; set; }
    }
}
